### ISSUE TITLE
Expects a ../maven.properties file

### ISSUE THREAD

**Issue by anidev** [Open-RIO/ToastAPI#1]
Building with gradle fails after not being able to find `../maven.properties`, in line 31 of build.gradle.

**Comment by JaciBrunning** [comment]
Remove the uploadArchives closure in the build.gradle, that's only for me publishing Toast

**Comment by anidev** [comment]
Could you fix the gradle file so it ignores the file if it doesn't exist instead of giving an error? Or at the very least mention something in the readme about how everyone needs to change this file after cloning in order to compile?

**Comment by anidev** [comment]
Furthermore, removing that closure isn't enough, lines 30-35 also need to be removed.

**Comment by JaciBrunning** [comment]
The project usually isn't meant to be build without maven, that is for when the Deployment tool gets released. I will try to fix the build.gradle to reflect this

**Comment by anidev** [comment]
I did have maven already installed and in my path, but no ../maven.properties file. Not sure if that is related in any way. Hopefully there will be a way to easily build afer cloning without having to modify files.

**Comment by JaciBrunning** [comment]
That's the thing. This is the src of the Toast program, so it has a maven.properties file to upload to maven for people to develop their plugins with
