### ISSUE TITLE
JScript not supported

### ISSUE THREAD

**Issue by WawerOS** [Open-RIO/ToastAPI#16]
My robot build fails with the message that JScript is not supported full crash log [here](https://up1.ca/#bBAXQT-AgN3qiqSVp5rDqQ).  So is there any way you know of to get it supported?

**Comment by JaciBrunning** [comment]
Could you also provide the crash log appended with `-FULL`? Thanks

**Comment by JaciBrunning** [comment]
Toast 2.4.4 should resolve the issue. Please run `gradlew dependencies` while connected to the internet, and then `gradlew toastDeploy` when connected to your RoboRIO. If any issues arise, feel free to reopen the issue.
