### ISSUE TITLE
Cannot find symbol CrashInfoToast

### ISSUE THREAD

**Issue by anidev** [Open-RIO/ToastAPI#2]
Build fails during compilation because the symbol CrashInfoToast could not be found. This happens in CrashHandler.java line 45. I couldn't find a file with CrashInfoToast as part of its name anywhere in the file tree, nor could I find the text CrashInfoToast in any file except the one that fails to compile.

I was trying to build by first running `./gradlew wpi` then `./gradlew build`, in case that might be relevant to the issue.

**Comment by JaciBrunning** [comment]
Re-Download the repository, the file should be added now

**Comment by anidev** [comment]
All right, it works now
