### ISSUE TITLE
Can't enter commands in toastconsole

### ISSUE THREAD

**Issue by floogulinc** [Open-RIO/ToastAPI#24]
I can't seem to enter commands in `gradle toastconsole`. I am running it on Windows and have tried in PowerShell, Command Prompt, and Git Bash.

**Comment by keplersj** [comment]
I can confirm with OS X's Terminal.

**Comment by JaciBrunning** [comment]
Commands can be entered, but they appear on the same line as the bold white text Gradle fixes to the bottom. ToastConsole reads from STDIN. Can you confirm this?

**Comment by JaciBrunning** [comment]
Fixed via `40a7114` in [GradleRIO](https://github.com/Open-RIO/GradleRIO/commit/40a7114d54ee271b4dcadf1a084ec26c193f8a32)
