### ISSUE TITLE
ToastAPI takes to long to start

### ISSUE THREAD

**Issue by WawerOS** [Open-RIO/ToastAPI#29]
The Toast startup procedure stalls after "Nuking Toast" and throws [this](https://gist.github.com/WawerOS/7a3496e0375d00d96a34) error in the logfile.

**Comment by JaciBrunning** [comment]
This log appears to be coming from a RoboRIO system.

This is not really an error. Toast will continue to boot, it's just noticed that it's been idle for a few minutes, and so prints out a stacktrace for if there's a potential bug. What's happening is that WPILib is waiting for a DriverStation to connect before continuing with the loading process. Once you connect a Driver Station, this should not happen, and your code should continue to run just fine
