### ISSUE TITLE
Unsupported Major.minor version

### ISSUE THREAD

**Issue by ghost** [Open-RIO/ToastAPI#4]
Hi. Tried compiling this and ended up with an unsupported major.minor version error. What should I do?
# 

06:34:58.273 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
06:34:58.274 [ERROR] [org.gradle.BuildExceptionReporter] 
06:34:58.275 [ERROR] [org.gradle.BuildExceptionReporter] \* Where:
06:34:58.276 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/home/matt/Projects/ToastAPI/build.gradle' line: 23
06:34:58.277 [ERROR] [org.gradle.BuildExceptionReporter] 
06:34:58.277 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
06:34:58.278 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'ToastAPI'.
06:34:58.279 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.UnsupportedClassVersionError: jaci/openrio/gradle/GradleRIO : Unsupported major.minor version 52.0
06:34:58.280 [ERROR] [org.gradle.BuildExceptionReporter] 
06:34:58.282 [ERROR] [org.gradle.BuildExceptionReporter] \* Try:
06:34:58.283 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
06:34:58.286 [LIFECYCLE] [org.gradle.BuildResultLogger] 
06:34:58.288 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
06:34:58.290 [LIFECYCLE] [org.gradle.BuildResultLogger] 
06:34:58.291 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 4.054 secs

**Comment by JaciBrunning** [comment]
Run `java -version` in a command prompt. The java version on your system should be the 8u25 JDK or higher

**Comment by ghost** [comment]
That would probably do it, JAVA_HOME was pointing to the wrong JDK installation and I didn't realize it
