### ISSUE TITLE
The roboRIO non-responsive, ran out of RAM. 

### ISSUE THREAD

**Issue by WawerOS** [Open-RIO/ToastAPI#42]
Upon updating to 4.11 our robot started to not respond to either teleop or to autonomous commands. the [toast logs](https://gist.github.com/WawerOS/4847179ffe86512a738ff567c58fd294) said nothing. But I found a JVM  [log](https://gist.github.com/WawerOS/511000d6cf1a63b95de385e78f9c9227) that seemed to indicate that the program consumed more ram than was allocated. So I have two questions. One can I allocate more ram? And two is there a way to restrain the ram usage?

**Comment by JaciBrunning** [comment]
Are you running more than one instance of the JVM on your RoboRIO? Toast's JVM usage is fairly minimal, although WPILib does raise it quite high. If you are running another JVM instance on your RoboRIO such as GRIP or (accidentally) starting a second FRC Instance, that could be causing your issue.

**Comment by WawerOS** [comment]
We're not not running another JVM. Only one to my knowledge. If it helps, occasionally eclipse complained about obsolete methods when running the code.

**Comment by JaciBrunning** [comment]
Do you have any modules deployed to the RoboRIO?

**Comment by WawerOS** [comment]
Yes Blackbox, newest version.

**Comment by JaciBrunning** [comment]
What version were you running before 2.4.11?

**Comment by WawerOS** [comment]
2.4.9.

**Comment by JaciBrunning** [comment]
See if you can get Toast to run with the `--debug` flag. You can do this by editing the `robotCommand` file under `/home/lvuser`. Send me the output and I'll see where things are being held up

**Comment by JaciBrunning** [comment]
`87b1116` (2.4.12) should fix the memory leaks. Let me know if it's still occuring, and if it is, downgrade to 2.4.9 while I attempt to find a fix
