### ISSUE TITLE
Deploy Failed

### ISSUE THREAD

**Issue by CS-5** [Open-RIO/ToastAPI#46]
Windows 10
Toast Version: 2.4.14
Intellij IDEA 2016.2.1

When I go to deploy my code, everything is fine until the deploy sequence. Error as follows: `server indicated an error: scp toast/modules/Khan-Mk.2.jar: No such file or directory`

I did notice that within the `run/toast/modules` directory, there were no .jar files to be found.

**Comment by JaciBrunning** [comment]
Gradle fetches deployment files from your build directory (`build/libs`). Does this folder contain any JAR files? If so, what is the filename?

**Comment by CS-5** [comment]
There is a .jar file matching the file which could not be found, in the libs folder:
`Khan-Mk.2`

**Comment by JaciBrunning** [comment]
Have you run `gradlew toastDeploy` yet? If not, run it to deploy Toast
itself to your RoboRIO. Allow Toast to run on your RoboRIO once before
attempting to deploy the module. This will allow Toast to create the
`/home/lvuser/toast/modules` directory on the RoboRIO, which is currently
missing thus causing a deployment error

**Comment by CS-5** [comment]
I see. I must have missed that in the documentation. Thank you, the deployment was a success.

**Comment by JaciBrunning** [comment]
No problem, I'll edit the docs tonight to point this step out more
prominently
