### ISSUE TITLE
How to build and use own version of ToastAPI for submodule?

### ISSUE THREAD

**Issue by primetoxinz** [Open-RIO/ToastAPI#47]
as per title.
made changes to the api and I want to test them out
basically just need to know the correct way to change the maven dependency to a local one
I tried a direct `compile files( "dir/../../Toast-<version>.jar")` but that didn't work

**Comment by JaciBrunning** [comment]
If you build and use your own version of ToastAPI, all modules loaded will use the same, modified version.

You will have to run 2 commands to do a clean build of Toast:
`gradlew build generateExternalPatches`
and `gradlew build`. 

The resulting file will be under `build/libs`. Don't forget to change the Toast Version in `build.settings` before building to avoid conflicts.

What changes did you make to the API? Some changes you can make without a rebuild through a module API call

**Comment by primetoxinz** [comment]
I was attempting to use avahi instead of dns-sd, since there is no bonjour for linux

**Comment by primetoxinz** [comment]
the module is still definitely using the maven dependency, not the local build

**Comment by JaciBrunning** [comment]
You can disable Toast's dns-sd from the Toast configuration file under `run/toast/config`. If you're looking to tunnel a Driver Station instance, you can either configure an Avahi service on your linux system as usual [avahi.service](http://linux.die.net/man/5/avahi.service) (you shouldn't need to rebuild Toast for this, you can do it in your normal userspace), or you can setup a dns-sd proxy on your Driver Station computer with the instructions [here](https://github.com/Open-RIO/ToastAPI/wiki/Simulating-Joysticks-and-the-Driver-Station#connecting-from-another-computers-driver-station).

To change your maven dependency to a local one, use `compile fileTree(include: '*.jar', dir: '<ToastDir>')`, substituting `<ToastDir>` for the `build/libs` directory of your local Toast instance. You will, however, need to add the other following compile dependencies to your build.gradle that Toast itself depends on:

```
compile 'jaci.openrio.delegate:NetworkDelegate:1.2.1'
compile 'com.grack:nanojson:+'
```

The `buildscript {}` portion of your config file should resemble [this](https://github.com/Open-RIO/ToastAPI/blob/development/build.gradle#L1-L14).

(for your module)
Run `./gradlew clean cleanIdea cleanEclipse`.
To build, run `./gradlew build --refresh-dependencies`
To get eclipse running, run `./gradlew eclipse --refresh-dependencies`. This same step applies for IntelliJ, replacing `eclipse` with `idea`

**Comment by primetoxinz** [comment]
okay, cool. have no experience with this kind of stuff, good to know! thanks

**Comment by JaciBrunning** [comment]
NOTE: Ignore the `buildscript {}` part of the previous comment. The `buildscript {}` block present in your existing build.gradle should be file, my apologies

**Comment by JaciBrunning** [comment]
No problem, feel free to reopen the issue if you have any more issues
